module.exports.RoleSystem = {
  ADMIN: 1, //Administrator
  NVKP: 2, //Nhân viên khoa phòng
  NVPVT: 3, //Nhân viên phòng vật tư
  DDT: 4, //Điều dưỡng trưởng
  GD: 5, //Giám đốc
  TK: 6, //Trưởng khoa
  TPVT: 7, //Trưởng phòng vật tư
  PTPVT: 8, //Phụ trách phòng vật tư
  USER: 9, //Người dùng mặc định
  GDPVT: 10,
  NVQLVT: 12,
};

module.exports.PermissionSystem = {
  DASHBOARD_READ: 160,
  DEPARTMENT_READ: 161,
  DEPARTMENT_CREATE: 162,
  DEPARTMENT_UPDATE: 163,
  DEPARTMENT_DELETE: 164,
  SETTING_INFO: 165,
  SETTING_ROLE: 166,
  USER_CREATE: 167,
  USER_READ: 168,
  USER_UPDATE: 169,
  USER_DELETE: 170,
  EQUIPMENT_CREATE: 171,
  EQUIPMENT_READ: 172,
  EQUIPMENT_UPDATE: 173,
  EQUIPMENT_DELETE: 174,
  UNIT_EQUIPMENT_CREATE: 175,
  UNIT_EQUIPMENT_READ: 176,
  UNIT_EQUIPMENT_UPDATE: 177,
  UNIT_EQUIPMENT_DELETE: 178,
  REPAIR_EQUIPMENT_CREATE: 179,
  REPAIR_EQUIPMENT_READ: 180,
  REPAIR_EQUIPMENT_UPDATE: 181,
  REPAIR_EQUIPMENT_DELETE: 182,
  REPORT_EQUIPMENT_CREATE: 183,
  REPORT_EQUIPMENT_READ: 184,
  REPORT_EQUIPMENT_UPDATE: 185,
  REPORT_EQUIPMENT_DELETE: 186,
  TRANFER_EQUIPMENT_CREATE: 187,
  TRANFER_EQUIPMENT_READ: 188,
  TRANFER_EQUIPMENT_UPDATE: 189,
  TRANFER_EQUIPMENT_APPROVE: 190,
  TRANFER_EQUIPMENT_DELETE: 191,
  LIQUIDATION_EQUIPMENT_CREATE: 192,
  LIQUIDATION_EQUIPMENT_READ: 193,
  LIQUIDATION_EQUIPMENT_UPDATE: 194,
  LIQUIDATION_EQUIPMENT_APPROVE: 195,
  APPROVE_ORDERS: 196,
  INBOUND_ORDERS_CREATE: 197,
  INBOUND_ORDERS_UPDATE: 198,
  INBOUND_ORDERS_READ: 199,
  INBOUND_ORDERS_DELETE: 200,
  OUTBOUND_ORDERS_CREATE: 201,
  OUTBOUND_ORDERS_UPDATE: 202,
  OUTBOUND_ORDERS_READ: 203,
  OUTBOUND_ORDERS_DELETE: 204,
  CONSUMABLE_SUPPLY_READ: 205,
  CONSUMABLE_SUPPLY_CREATE: 206,
  CONSUMABLE_SUPPLY_UPDATE: 207,
  CONSUMABLE_SUPPLY_DELETE: 208,
  WAREHOUSES_MANAGEMENT_READ:209,
  WAREHOUSES_MANAGEMENT_UPDATE:210,
  WAREHOUSES_MANAGEMENT_CREATE:211,
  WAREHOUSES_MANAGEMENT_DELETE: 212,
};

module.exports.REPORT = {
  RECEIVE_HANDOVER: 1,
  RECEIVE_REQUEST_BROKEN: 2,
  RECEIVE_APPROVE_BROKEN: 3,
  RECEIVE_REQUEST_REPAIR: 4,
  RECEIVE_APPROVE_REPAIR: 5,
  RECEIVE_ACCEPTANCE_REPAIR: 6,
  RECEIVE_REHANDOVER: 7,
  RECEIVE_REQUEST_INSPECTION: 8,
  RECEIVE_APPROVE_INSPECTION: 9,
  RECEIVE_REQUEST_TRANSFER: 10,
  RECEIVE_APPROVE_TRANSFER: 11,
  RECEIVE_REQUEST_LIQUIDATION: 12,
  RECEIVE_APPROVE_LIQUIDATION: 13,
};